# Generated by Django 3.0.4 on 2020-05-18 02:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('insta_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(null=True, upload_to='posts'),
        ),
        migrations.AlterField(
            model_name='post',
            name='uploaded_on',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 18, 2, 22, 46, 54096, tzinfo=utc)),
        ),
    ]
